// doNotTrack.ts — the ONE definition of "this traffic is the founder's and is never counted."
//
// Founder decision (2026-08-25): metrics generated by Josh's own devices and accounts must not
// be recorded anywhere in the app. Two mechanisms, one module:
//
//   1. DEVICE — the `crwn_dnt` cookie. useAuth sets it for a year the first time an admin
//      profile loads in a browser, so every later request from that device carries it: logged
//      in, logged out, or signed into a different account (the m3rcey test artist included).
//      Every tracking WRITE path checks it: middleware's visit tracking, /api/tier-events,
//      /api/funnel/track, /api/lead-magnets/analytics, /api/popups, /api/admin/track, and the
//      player's play logging.
//   2. ACCOUNT — role = 'admin'. recordFunnelEvent skips events attributed to an admin user id,
//      which covers server-side call sites (webhooks, auto-claim) that never see the cookie.
//
// This is an ANALYTICS exclusion only. It must never gate a product behavior, an entitlement,
// or an authorization: a visitor who hand-sets this cookie opts out of being counted, which is
// a right, not a privilege escalation. If you add a new tracking write path, check this module
// in it (that rule lives in CLAUDE.md).
//
// Pure string/document logic only — no Node built-ins — so it is safe in the Edge runtime
// (middleware), Node route handlers, and client components alike.

export const DNT_COOKIE_NAME = 'crwn_dnt';

/** One year. The cookie is re-set on every admin profile load, so it never really expires. */
export const DNT_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365;

/** True when a raw Cookie header marks this device as never-counted. */
export function hasDntCookie(cookieHeader: string | null | undefined): boolean {
  if (!cookieHeader) return false;
  return /(?:^|;\s*)crwn_dnt=1(?:;|\s|$)/.test(cookieHeader);
}

/** The header subset a route needs. Works for a NextRequest, a Request, or plain Headers. */
export interface CookieHeaders {
  get(name: string): string | null;
}

/** True when the request comes from a never-counted device. Use this in tracking API routes. */
export function requestHasDnt(headers: CookieHeaders): boolean {
  return hasDntCookie(headers.get('cookie'));
}

/** Client-side check for tracking that writes from the browser (play logging). */
export function clientHasDnt(): boolean {
  if (typeof document === 'undefined') return false;
  return hasDntCookie(document.cookie);
}

/** Mark this browser as never-counted. Called by useAuth when an admin profile loads. */
export function markDeviceDnt(): void {
  if (typeof document === 'undefined') return;
  document.cookie = `${DNT_COOKIE_NAME}=1; path=/; max-age=${DNT_COOKIE_MAX_AGE_SECONDS}; SameSite=Lax`;
}
