// Quest Engine — the template catalog (code = source of truth).
//
// These definitions are STATIC config, like the thresholds in src/lib/milestones.ts.
// syncTemplatesToDb() upserts them into quest_templates by `key` so the DB has a
// queryable catalog; AI/admin/artist-authored quests can also be inserted there.
//
// This Phase-1 seed is a REPRESENTATIVE connected set (artist Levels 1-3, fan
// Stages 1-2) that proves the engine end to end, not the full spec catalogue.
// Adding the rest is data entry against this same shape.

import type { QuestTemplate } from './types';

// ---------------------------------------------------------------------------
// ARTIST — Tutorial (Enter the Kingdom) + Level 1 (Foundation) + Level 2 (Vault)
// + Level 3 (Membership Ladder). The Tutorial is the /setup wizard; its two
// quests are grouped under 'foundation' and auto-recognized once the wizard runs.
// ---------------------------------------------------------------------------
const ARTIST_SETUP: QuestTemplate[] = [
  // ---- Tutorial: Enter the Kingdom ----
  {
    key: 'artist_add_photo',
    title: 'Add your artist photo',
    subtitle: 'Make your CRWN look real',
    whyItMatters: 'Supporters trust a face. A photo lifts profile conversion more than any other single field.',
    category: 'setup',
    questType: 'onboarding_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: 'under 2 minutes',
    levelKey: 'foundation',
    completionCondition: { kind: 'domain', check: 'artist_has_avatar' },
    reward: { xp: 25, badges: [], unlocks: ['rise_feed'] },
    priorityScore: 300,
    sortOrder: 10,
  },
  {
    key: 'artist_upload_first_track',
    title: 'Upload a track fans can’t get anywhere else',
    subtitle: 'An unreleased song, demo, or exclusive',
    whyItMatters:
      'A fan needs a reason to follow you HERE instead of just streaming you. Something they can only get on your CRWN is that reason.',
    category: 'setup',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'foundation',
    steps: [
      { title: 'Pick a track fans can’t hear elsewhere' },
      { title: 'Upload it' },
      { title: 'Choose who gets it (free or supporters)' },
    ],
    completionCondition: { kind: 'domain', check: 'artist_has_track' },
    reward: { xp: 50 },
    priorityScore: 290,
    sortOrder: 20,
  },

  // ---- Level 1: Build Your Foundation ----
  {
    key: 'artist_add_socials',
    title: 'Link your socials and platforms',
    subtitle: 'Point your whole audience at one home',
    whyItMatters:
      'Your links turn scattered followers into one owned audience. A fan who finds you anywhere can land here.',
    category: 'setup',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: 'under 2 minutes',
    levelKey: 'foundation',
    completionCondition: { kind: 'domain', check: 'artist_has_socials' },
    reward: { xp: 25 },
    priorityScore: 245,
    sortOrder: 30,
  },
  {
    key: 'artist_complete_profile',
    title: 'Complete Your Artist Destination',
    subtitle: 'A public page credible enough to share',
    whyItMatters:
      'This is your front door. Fans decide in seconds whether to support you. A photo, banner, bio, a track, and a link are what turn a profile into a destination worth sharing.',
    category: 'setup',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '10 minutes',
    levelKey: 'foundation',
    prerequisites: ['artist_add_photo'],
    steps: [
      { title: 'Add a banner image' },
      { title: 'Write a short bio' },
      { title: 'Add a tagline' },
      { title: 'Add a social or external link' },
      { title: 'Review your artist URL' },
      { title: 'Preview your page as a fan (desktop and mobile)' },
    ],
    // Authoritative: photo + banner + bio + claimed URL + a track + at least one link.
    completionCondition: { kind: 'domain', check: 'artist_destination_complete' },
    reward: { xp: 100, badges: ['destination_complete'] },
    priorityScore: 240,
    sortOrder: 40,
  },

  // ---- Level 2: Build Your Vault ----
  {
    key: 'artist_catalog_depth',
    title: 'Build out your catalog',
    subtitle: 'Give fans more than one reason to stay',
    whyItMatters:
      'One track is a sample. A few tracks is a catalog worth subscribing to. Add your strongest released song, your newest release, and one more.',
    category: 'content',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '15 minutes',
    levelKey: 'vault',
    prerequisites: ['artist_upload_first_track'],
    steps: [
      { title: 'Add your strongest released song' },
      { title: 'Add your newest release' },
      { title: 'Add one more important track' },
      { title: 'Set who gets each track (free or supporters)' },
    ],
    // Three tracks total is a real catalog without demanding a full upload from
    // day one. Established artists auto-clear this instantly from existing tracks.
    completionCondition: { kind: 'domain', check: 'artist_track_count', count: 3 },
    reward: { xp: 100, badges: ['vault_started'] },
    priorityScore: 235,
    sortOrder: 10,
  },
  {
    key: 'artist_first_album',
    title: 'Organize a release into an album',
    subtitle: 'Group your work so fans can dig in',
    whyItMatters: 'An album turns loose tracks into a body of work. It is how supporters browse and rediscover you.',
    category: 'content',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'vault',
    prerequisites: ['artist_upload_first_track'],
    completionCondition: { kind: 'domain', check: 'artist_has_album' },
    reward: { xp: 75 },
    priorityScore: 225,
    sortOrder: 20,
  },
  {
    key: 'artist_first_playlist',
    title: 'Create a playlist for fans',
    subtitle: 'Curate a way in for new listeners',
    whyItMatters: 'A playlist is a guided tour of your best work: the fastest way for a new fan to fall in.',
    category: 'content',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '5 minutes',
    levelKey: 'vault',
    prerequisites: ['artist_upload_first_track'],
    completionCondition: { kind: 'domain', check: 'artist_has_playlist' },
    reward: { xp: 50 },
    priorityScore: 220,
    sortOrder: 30,
  },

  // ---- Level 3: Build Your Membership Ladder ----
  {
    key: 'artist_create_free_tier',
    title: 'Create your free tier',
    subtitle: 'Your front door: the easiest yes',
    whyItMatters:
      'A free tier is the top of your funnel. Casual listeners join for free, land on your list, and become the people you later convert to paid supporters. It never counts against your plan limit.',
    category: 'offer',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '5 minutes',
    requiredFeature: 'offer_builder',
    levelKey: 'ladder',
    // NOTE: no longer chained behind nothing but the track. It is NOT a prereq of
    // the paid tier (that chain could deadlock a capped plan whose one tier is paid).
    prerequisites: ['artist_upload_first_track'],
    steps: [
      { title: 'Name it (e.g. “Community”)' },
      { title: 'Keep the price at $0' },
      { title: 'Add what free followers get' },
      { title: 'Publish' },
    ],
    completionCondition: { kind: 'domain', check: 'artist_has_free_tier' },
    reward: { xp: 50, unlocks: ['supporter_leaderboard'] },
    priorityScore: 215,
    sortOrder: 40,
  },
  {
    key: 'artist_build_first_offer',
    title: 'Create a paid supporter tier',
    subtitle: 'Load it with the exclusives only supporters get',
    whyItMatters:
      'This is where fans become income. Put your best assets behind it (unreleased tracks, behind-the-scenes, early access) so supporting you is an obvious deal.',
    category: 'offer',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '10 minutes',
    requiredFeature: 'offer_builder',
    levelKey: 'ladder',
    prerequisites: ['artist_upload_first_track'],
    steps: [
      { title: 'Set a monthly price' },
      { title: 'Add what supporters get: exclusive tracks, perks, early access' },
      { title: 'Publish' },
    ],
    completionCondition: { kind: 'domain', check: 'artist_has_paid_offer' },
    reward: { xp: 100, badges: ['first_offer_built'], content: ['rise_feed_offer_post'] },
    priorityScore: 210,
    sortOrder: 50,
    generatesFanQuests: ['fan_subscribe_to_artist'],
  },
  {
    key: 'artist_tier_benefits',
    title: 'Load your tiers with real benefits',
    subtitle: 'Make supporting you an obvious deal',
    whyItMatters:
      'Benefits are the reason to pay. Exclusive tracks, early access, and a shop discount turn a price into value fans want.',
    category: 'offer',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '5 minutes',
    levelKey: 'ladder',
    prerequisites: ['artist_build_first_offer'],
    completionCondition: { kind: 'domain', check: 'artist_tier_has_benefits' },
    reward: { xp: 50 },
    priorityScore: 205,
    sortOrder: 60,
  },
  {
    key: 'artist_ladder_complete',
    title: 'Complete your membership ladder',
    subtitle: 'Give fans a way to go deeper',
    whyItMatters:
      'A ladder lets your biggest fans pay you more. Apply the recommended tiers, then edit them to fit your world. Your plan sets how many paid tiers you can run.',
    category: 'offer',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '10 minutes',
    requiredFeature: 'offer_builder',
    levelKey: 'ladder',
    prerequisites: ['artist_build_first_offer'],
    steps: [
      { title: 'Review the recommended four-tier template' },
      { title: 'Apply the tiers that fit you' },
      { title: 'Edit names, prices, and benefits' },
      { title: 'Preview the ladder as a fan' },
    ],
    // Plan-aware: done at min(3, plan paid-cap). Starter completes at 1 paid tier,
    // Pro at 3. Never uncompletable, never bypasses a plan limit.
    completionCondition: { kind: 'domain', check: 'artist_ladder_complete' },
    reward: { xp: 200, badges: ['ladder_built'] },
    priorityScore: 200,
    sortOrder: 70,
  },
];

// ---------------------------------------------------------------------------
// ARTIST — Level 4: Open the Gates (connect Stripe, make tiers purchasable,
// welcome your first members). Boss = a genuinely charges-enabled Stripe account.
// ---------------------------------------------------------------------------
const ARTIST_OPEN_GATES: QuestTemplate[] = [
  {
    key: 'artist_stripe_connect',
    title: 'Connect Stripe and open for payments',
    subtitle: 'Turn on the ability to get paid',
    whyItMatters:
      'Nothing sells until Stripe is connected. This is the switch that lets fans actually support you. It only counts once your account can truly take money.',
    category: 'setup',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '10 minutes',
    levelKey: 'open_gates',
    prerequisites: ['artist_build_first_offer'],
    steps: [
      { title: 'Start Stripe onboarding' },
      { title: 'Submit your details' },
      { title: 'Confirm your account can take payments' },
    ],
    completionCondition: { kind: 'domain', check: 'artist_stripe_connected' },
    reward: { xp: 300, badges: ['gates_open'], unlocks: ['payments_live'] },
    priorityScore: 195,
    sortOrder: 10,
  },
  {
    key: 'artist_tier_purchasable',
    title: 'Make your paid tiers purchasable',
    subtitle: 'Confirm your tiers are ready to sell',
    whyItMatters:
      'A paid tier only earns once it has a live price. CRWN backfills prices for tiers you built before connecting, so this usually finishes itself right after Stripe connects.',
    category: 'offer',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '2 minutes',
    levelKey: 'open_gates',
    prerequisites: ['artist_stripe_connect'],
    completionCondition: { kind: 'domain', check: 'artist_tier_purchasable' },
    reward: { xp: 100 },
    priorityScore: 190,
    sortOrder: 20,
  },
  {
    key: 'artist_welcome_post',
    title: 'Post a welcome to your community',
    subtitle: 'Give new members a reason they made the right call',
    whyItMatters:
      'The first thing a new supporter sees should be you. A welcome post tells fans why they are here and what is coming.',
    category: 'content',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '5 minutes',
    levelKey: 'open_gates',
    prerequisites: ['artist_stripe_connect'],
    steps: [
      { title: 'Write a short welcome' },
      { title: 'Explain why fans should join' },
      { title: 'Post it to your community' },
    ],
    completionCondition: { kind: 'domain', check: 'artist_has_community_post' },
    reward: { xp: 100, badges: ['first_post'] },
    priorityScore: 185,
    sortOrder: 30,
  },
  {
    key: 'artist_infrastructure_ready',
    title: 'Open Your CRWN',
    subtitle: 'Your full fan infrastructure is live and tested',
    whyItMatters:
      'Everything a fan needs now exists: a credible page, an organized catalog, a membership ladder, payments, a free path, a paid path, and a welcome. You are ready to recruit fans.',
    category: 'setup',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'boss',
    estimatedTime: 'the setup journey',
    levelKey: 'open_gates',
    // Authoritative composite of the whole L1-L4 foundation. Marks the artist
    // infrastructure-ready WITHOUT overloading setup_completed (the initial gate).
    prerequisites: ['artist_stripe_connect'],
    completionCondition: { kind: 'domain', check: 'artist_infrastructure_ready' },
    reward: { xp: 400, badges: ['infrastructure_ready'], unlocks: ['growth_stage'] },
    priorityScore: 183,
    sortOrder: 40,
  },
];

// ---------------------------------------------------------------------------
// ARTIST — Level 5: Founding Fans (seeded here; templates authored in a later prompt)
// ---------------------------------------------------------------------------
const ARTIST_FIRST_SUPPORTERS: QuestTemplate[] = [
  // ---- Level 5: Recruit Your Founding Fans (mini-boss = first free member, boss = first paid) ----
  {
    key: 'artist_prospect_list',
    title: 'Build a founding-fan prospect list',
    subtitle: 'Name the people most likely to support you first',
    whyItMatters:
      'Your first supporters are people who already know you. Import contacts and list your likeliest 25 so your launch has somewhere to land.',
    category: 'promotion',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '15 minutes',
    levelKey: 'founding_fans',
    prerequisites: ['artist_stripe_connect'],
    completionCondition: { kind: 'domain', check: 'artist_has_fan_contacts', count: 1 },
    reward: { xp: 75 },
    priorityScore: 184,
    sortOrder: 5,
  },
  {
    key: 'artist_invite_five',
    title: 'Invite your first five personally',
    subtitle: 'A direct message beats any broadcast',
    whyItMatters: 'The first five supporters almost never come from a post. They come from you reaching out one to one.',
    category: 'promotion',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '20 minutes',
    levelKey: 'founding_fans',
    prerequisites: ['artist_stripe_connect'],
    // Coaching action with no product signal: manual completion (never financial).
    completionCondition: { kind: 'manual' },
    reward: { xp: 75 },
    priorityScore: 182,
    sortOrder: 6,
  },
  {
    key: 'artist_launch_announcement',
    title: 'Publish your CRWN launch announcement',
    subtitle: 'Tell your audience where to find you now',
    whyItMatters: 'People cannot support what they do not know exists. Announce your CRWN and share an exclusive preview.',
    category: 'content',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'founding_fans',
    prerequisites: ['artist_stripe_connect'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 75 },
    priorityScore: 181,
    sortOrder: 7,
  },
  {
    key: 'artist_first_free_member',
    title: 'Get your first free member',
    subtitle: 'The top of your funnel comes alive',
    whyItMatters: 'A free member is a warm lead you now own. It is the first proof your front door works.',
    category: 'support',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: 'multi-day',
    levelKey: 'founding_fans',
    prerequisites: ['artist_create_free_tier'],
    completionCondition: { kind: 'domain', check: 'artist_free_supporter_count', count: 1 },
    reward: { xp: 150, badges: ['first_free_member'] },
    priorityScore: 178,
    sortOrder: 8,
  },
  {
    key: 'artist_founder_story',
    title: 'Publish your founder story',
    subtitle: 'Give fans a reason to believe now',
    whyItMatters: 'People back people. A short founder story is the difference between a follow and a first payment.',
    category: 'content',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '15 minutes',
    levelKey: 'founding_fans',
    prerequisites: ['artist_stripe_connect'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 50 },
    priorityScore: 176,
    sortOrder: 9,
  },
  {
    key: 'artist_first_supporter',
    title: 'Get your first paid supporter',
    subtitle: 'Turn attention into your first believer',
    whyItMatters: 'The first dollar is the hardest and the most important. It proves the model works for you.',
    category: 'support',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'hard',
    estimatedTime: 'multi-day',
    levelKey: 'founding_fans',
    prerequisites: ['artist_stripe_connect'],
    completionCondition: { kind: 'domain', check: 'artist_supporter_count', count: 1 },
    reward: { xp: 250, badges: ['first_supporter'], content: ['thank_you_draft'], notifyFans: true },
    priorityScore: 175,
    sortOrder: 10,
  },
  {
    key: 'artist_thank_supporter',
    title: 'Thank your first supporter and ask why they joined',
    subtitle: 'The most valuable feedback you will ever get',
    whyItMatters:
      'Thanking your first supporter earns loyalty, and asking why they joined tells you exactly how to get the next ten.',
    category: 'support',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'founding_fans',
    prerequisites: ['artist_first_supporter'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 75 },
    priorityScore: 172,
    sortOrder: 11,
  },

  // ---- Level 6: Build the First 10 (boss = ten paid supporters) ----
  {
    key: 'artist_first_members_post',
    title: 'Publish your first members-only post',
    subtitle: 'Deliver the exclusive you promised',
    whyItMatters: 'A members-only post is the first proof that paying is worth it. Deliver early and supporters stay.',
    category: 'content',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'first_ten',
    prerequisites: ['artist_first_supporter'],
    completionCondition: { kind: 'domain', check: 'artist_members_post_count', count: 1 },
    reward: { xp: 100, badges: ['first_members_post'] },
    priorityScore: 170,
    sortOrder: 12,
  },
  {
    key: 'artist_ask_referral',
    title: 'Ask a supporter for a referral',
    subtitle: 'Your happiest fan is your best channel',
    whyItMatters: 'Referrals from real supporters convert better than any ad. Ask, and share the proof publicly.',
    category: 'promotion',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'first_ten',
    prerequisites: ['artist_first_supporter'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 75 },
    priorityScore: 169,
    sortOrder: 13,
  },
  {
    key: 'artist_five_supporters',
    title: 'Reach five paid supporters',
    subtitle: 'Halfway to real momentum',
    whyItMatters: 'Five supporters proves the first one was not a fluke. The path to ten is the same path repeated.',
    category: 'support',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'hard',
    estimatedTime: 'multi-day',
    levelKey: 'first_ten',
    prerequisites: ['artist_first_supporter'],
    completionCondition: { kind: 'domain', check: 'artist_supporter_count', count: 5 },
    reward: { xp: 200, badges: ['five_supporters'] },
    priorityScore: 168,
    sortOrder: 14,
  },
  {
    key: 'artist_founding_badge',
    title: 'Create a founding-member badge',
    subtitle: 'Make being early feel special',
    whyItMatters: 'A founding badge rewards the people who believed first and gives new fans a reason to hurry.',
    category: 'content',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '5 minutes',
    levelKey: 'first_ten',
    prerequisites: ['artist_first_supporter'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 50 },
    priorityScore: 167,
    sortOrder: 15,
  },
  {
    key: 'artist_ten_supporters',
    title: 'Reach 10 supporters',
    subtitle: 'Your CRWN is officially moving',
    whyItMatters: 'Ten paying supporters is real momentum. That is enough signal to justify campaigns and missions.',
    category: 'support',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'boss',
    estimatedTime: 'multi-day',
    levelKey: 'first_ten',
    prerequisites: ['artist_first_supporter'],
    completionCondition: { kind: 'domain', check: 'artist_supporter_count', count: 10 },
    reward: {
      xp: 500,
      badges: ['first_10_supporters'],
      unlocks: ['fan_missions', 'campaign_hub'],
      content: ['milestone_post_draft'],
      notifyFans: true,
    },
    priorityScore: 165,
    sortOrder: 20,
  },
];

// ---------------------------------------------------------------------------
// ARTIST — Level 7: Turn Fans Into a Community (boss = first retention cycle)
// ---------------------------------------------------------------------------
const ARTIST_COMMUNITY: QuestTemplate[] = [
  {
    key: 'artist_members_rhythm',
    title: 'Publish three members-only posts',
    subtitle: 'Turn a tier into a habit fans rely on',
    whyItMatters: 'Retention is a rhythm, not a launch. Three members-only posts is the start of a reason to stay.',
    category: 'content',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: 'over a week',
    levelKey: 'community_os',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_members_post_count', count: 3 },
    reward: { xp: 150, badges: ['community_rhythm'] },
    priorityScore: 158,
    sortOrder: 10,
  },
  {
    key: 'artist_host_live',
    title: 'Host your first group session',
    subtitle: 'A livestream, listening party, or Q&A',
    whyItMatters: 'Live moments are the strongest retention tool you have. One session turns supporters into regulars.',
    category: 'live',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '1 hour',
    requiredFeature: 'live',
    levelKey: 'community_os',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_went_live' },
    reward: { xp: 150, badges: ['first_live'] },
    canStreamLive: true,
    priorityScore: 156,
    sortOrder: 20,
  },
  {
    key: 'artist_collect_feedback',
    title: 'Collect supporter preference feedback',
    subtitle: 'Let members tell you what they want more of',
    whyItMatters: 'A single survey turns guesswork into a plan. Your members will tell you what keeps them if you ask.',
    category: 'retention',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'community_os',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_has_survey_response' },
    reward: { xp: 100 },
    priorityScore: 154,
    sortOrder: 30,
  },
  {
    key: 'artist_member_content_plan',
    title: 'Create a 30-day member content plan',
    subtitle: 'Decide what supporters get for the next month',
    whyItMatters: 'A plan you can keep beats a promise you cannot. Map the next 30 days so fulfillment never slips.',
    category: 'calendar',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '30 minutes',
    levelKey: 'community_os',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 100 },
    priorityScore: 152,
    sortOrder: 40,
  },
  {
    key: 'artist_run_poll',
    title: 'Let fans vote on a creative decision',
    subtitle: 'Give supporters a real say',
    whyItMatters: 'Voting turns passive members into co-creators. People protect what they helped decide.',
    category: 'fan_activation',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '5 minutes',
    levelKey: 'community_os',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 50 },
    priorityScore: 150,
    sortOrder: 50,
  },
  {
    key: 'artist_retention_cycle',
    title: 'Complete your first retention cycle',
    subtitle: 'Supporters who stay past a full billing period',
    whyItMatters:
      'The whole model rests on retention. Keeping a supporter through a full cycle while delivering members content proves it works.',
    category: 'retention',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'boss',
    estimatedTime: 'a billing period',
    levelKey: 'community_os',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_retention_cycle' },
    reward: { xp: 400, badges: ['first_retention_cycle'], unlocks: ['road_to_pages'] },
    priorityScore: 148,
    sortOrder: 60,
  },
];

// ---------------------------------------------------------------------------
// ARTIST — Level 8: Launch Your First Movement (learning boss = a closed campaign
// lifecycle; hitting the target is an enhanced success rank on top).
// ---------------------------------------------------------------------------
const ARTIST_CAMPAIGN_STARTER: QuestTemplate[] = [
  {
    key: 'artist_validate_demand',
    title: 'Validate your goal with Proof of Demand',
    subtitle: 'Test the idea before you build the campaign',
    whyItMatters: 'A quick demand test tells you if fans want it, so you rally around a goal that will actually land.',
    category: 'campaign',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'first_movement',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_has_proof_of_demand' },
    reward: { xp: 75 },
    priorityScore: 149,
    sortOrder: 5,
  },
  {
    key: 'artist_create_road_campaign',
    title: 'Launch your first Road To campaign',
    subtitle: 'Give fans a goal to rally around',
    whyItMatters: 'A campaign converts passive fans into active backers with a shared finish line.',
    category: 'campaign',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '15 minutes',
    requiredFeature: 'campaign_hub',
    levelKey: 'first_movement',
    prerequisites: ['artist_ten_supporters'],
    steps: [
      { title: 'Name your campaign' },
      { title: 'Set a goal' },
      { title: 'Choose rewards' },
      { title: 'Attach an offer' },
      { title: 'Launch' },
    ],
    completionCondition: { kind: 'domain', check: 'artist_has_campaign' },
    reward: { xp: 250, badges: ['campaign_starter'], unlocks: ['road_to_pages'], content: ['campaign_share_card'] },
    canStreamLive: true,
    priorityScore: 150,
    sortOrder: 10,
    generatesFanQuests: ['fan_back_campaign', 'fan_share_campaign', 'fan_invite_friend'],
  },
  {
    key: 'artist_create_missions',
    title: 'Create fan missions for your campaign',
    subtitle: 'Give supporters concrete ways to help',
    whyItMatters: 'Missions turn "please share" into a game fans want to play. They are how a campaign spreads.',
    category: 'fan_activation',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'first_movement',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_has_mission' },
    reward: { xp: 100 },
    priorityScore: 147,
    sortOrder: 20,
  },
  {
    key: 'artist_recruit_squad',
    title: 'Create or recruit a squad',
    subtitle: 'Build a core team that pushes with you',
    whyItMatters: 'A squad multiplies your reach. A handful of committed fans out-promotes any single post.',
    category: 'fan_activation',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '15 minutes',
    levelKey: 'first_movement',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_has_squad' },
    reward: { xp: 75 },
    priorityScore: 145,
    sortOrder: 30,
  },
  {
    key: 'artist_campaign_updates',
    title: 'Publish progress updates and a final push',
    subtitle: 'Keep the momentum visible',
    whyItMatters: 'Campaigns are won in the updates. Fans back what feels alive, and a final push converts the fence-sitters.',
    category: 'campaign',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: 'over the campaign',
    levelKey: 'first_movement',
    prerequisites: ['artist_create_road_campaign'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 100 },
    priorityScore: 143,
    sortOrder: 40,
  },
  {
    key: 'artist_campaign_closed',
    title: 'Complete your first campaign lifecycle',
    subtitle: 'Launch, communicate, and close it properly',
    whyItMatters:
      'Finishing a campaign the right way, whether or not you hit the number, teaches the loop you will run again and again.',
    category: 'campaign',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'boss',
    estimatedTime: 'multi-day',
    levelKey: 'first_movement',
    prerequisites: ['artist_create_road_campaign'],
    completionCondition: { kind: 'domain', check: 'artist_campaign_closed' },
    reward: { xp: 350, badges: ['first_movement'] },
    priorityScore: 141,
    sortOrder: 50,
  },
  {
    key: 'artist_campaign_reached',
    title: 'Hit your campaign goal',
    subtitle: 'The success rank on top of finishing',
    whyItMatters: 'Finishing teaches the loop. Hitting the target proves your movement can move the number.',
    category: 'campaign',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'hard',
    estimatedTime: 'multi-day',
    levelKey: 'first_movement',
    prerequisites: ['artist_create_road_campaign'],
    completionCondition: { kind: 'domain', check: 'artist_campaign_reached' },
    reward: { xp: 250, badges: ['campaign_won'] },
    priorityScore: 139,
    sortOrder: 60,
  },
];

// ---------------------------------------------------------------------------
// ARTIST — Level 9: Build the Growth Engine (boss = a repeatable fan journey SYSTEM;
// existence-based, never claims attribution causation).
// ---------------------------------------------------------------------------
const ARTIST_GROWTH: QuestTemplate[] = [
  {
    key: 'artist_smart_link',
    title: 'Create your primary smart link',
    subtitle: 'One link that captures fans everywhere',
    whyItMatters: 'A smart link is the top of your growth engine. Every bio, caption, and post should point here.',
    category: 'promotion',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'growth_engine',
    prerequisites: ['artist_create_road_campaign'],
    completionCondition: { kind: 'domain', check: 'artist_has_smart_link' },
    reward: { xp: 100 },
    priorityScore: 130,
    sortOrder: 10,
  },
  {
    key: 'artist_capture_lead',
    title: 'Capture your first fan contact',
    subtitle: 'Turn a click into an owned lead',
    whyItMatters: 'Contacts you own are worth more than followers you rent. Capture emails so you can bring fans back.',
    category: 'promotion',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: 'ongoing',
    levelKey: 'growth_engine',
    prerequisites: ['artist_smart_link'],
    completionCondition: { kind: 'domain', check: 'artist_captured_lead' },
    reward: { xp: 100 },
    priorityScore: 128,
    sortOrder: 20,
  },
  {
    key: 'artist_welcome_sequence',
    title: 'Activate a welcome sequence',
    subtitle: 'Greet every new fan automatically',
    whyItMatters: 'A welcome sequence works while you sleep. It walks a new free fan toward becoming a paid supporter.',
    category: 'offer',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '20 minutes',
    levelKey: 'growth_engine',
    prerequisites: ['artist_create_road_campaign'],
    completionCondition: { kind: 'domain', check: 'artist_has_active_sequence' },
    reward: { xp: 125 },
    priorityScore: 126,
    sortOrder: 30,
  },
  {
    key: 'artist_activate_referrals',
    title: 'Activate your referral program',
    subtitle: 'Let fans earn by bringing fans',
    whyItMatters: 'Referrals are the cheapest growth you will ever get. Turn it on so your supporters become your sales team.',
    category: 'promotion',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '5 minutes',
    levelKey: 'growth_engine',
    prerequisites: ['artist_create_road_campaign'],
    completionCondition: { kind: 'domain', check: 'artist_referrals_on' },
    reward: { xp: 100 },
    priorityScore: 124,
    sortOrder: 40,
  },
  {
    key: 'artist_recruit_clipper',
    title: 'Recruit your first promoter or clipper',
    subtitle: 'Put your content to work for reach',
    whyItMatters: 'Clippers turn your moments into reach you could never buy. Turn the program on and invite one.',
    category: 'promotion',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '10 minutes',
    requiredFeature: 'clipper',
    levelKey: 'growth_engine',
    prerequisites: ['artist_create_road_campaign'],
    completionCondition: { kind: 'domain', check: 'artist_clipper_on' },
    reward: { xp: 75 },
    priorityScore: 122,
    sortOrder: 50,
  },
  {
    key: 'artist_send_campaign',
    title: 'Send an email campaign',
    subtitle: 'Reach your whole list at once',
    whyItMatters: 'Your list is an asset only if you use it. One good send can move more fans than a week of posting.',
    category: 'promotion',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '20 minutes',
    levelKey: 'growth_engine',
    prerequisites: ['artist_capture_lead'],
    completionCondition: { kind: 'domain', check: 'artist_sent_campaign' },
    reward: { xp: 75 },
    priorityScore: 120,
    sortOrder: 60,
  },
  {
    key: 'artist_growth_loop',
    title: 'Prove your repeatable fan journey',
    subtitle: 'Discover, join free, engage, upgrade, stay, refer',
    whyItMatters:
      'When a free front door, a paid path, real supporters, and a reach mechanism are all live, you have a system you can run on repeat.',
    category: 'revenue',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'boss',
    estimatedTime: 'multi-week',
    levelKey: 'growth_engine',
    prerequisites: ['artist_smart_link', 'artist_activate_referrals'],
    completionCondition: { kind: 'domain', check: 'artist_growth_loop' },
    reward: { xp: 500, badges: ['growth_engine'], unlocks: ['growth_engine_tools'] },
    priorityScore: 118,
    sortOrder: 70,
  },
];

// ---------------------------------------------------------------------------
// ARTIST — Level 10: Become the Artist CEO (final boss = a self-sustaining business,
// which is also the main-game victory).
// ---------------------------------------------------------------------------
const ARTIST_CEO: QuestTemplate[] = [
  {
    key: 'artist_review_revenue',
    title: 'Review your revenue and best tier',
    subtitle: 'Know what is actually working',
    whyItMatters: 'You cannot grow what you do not measure. Find your strongest tier and your best-performing benefits.',
    category: 'revenue',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '15 minutes',
    levelKey: 'artist_ceo',
    prerequisites: ['artist_growth_loop'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 100 },
    priorityScore: 110,
    sortOrder: 10,
  },
  {
    key: 'artist_prune_promise',
    title: 'Revise or remove an unsustainable promise',
    subtitle: 'Protect the business from burnout',
    whyItMatters: 'A benefit you cannot keep costs you trust and time. Cut or reshape anything you cannot deliver reliably.',
    category: 'revenue',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'easy',
    estimatedTime: '10 minutes',
    levelKey: 'artist_ceo',
    prerequisites: ['artist_growth_loop'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 100 },
    priorityScore: 108,
    sortOrder: 20,
  },
  {
    key: 'artist_operating_calendar',
    title: 'Create a monthly operating calendar',
    subtitle: 'Set your release, community, and fulfillment rhythm',
    whyItMatters: 'A calendar turns your business from reactive to reliable. Rhythm is what keeps supporters paying.',
    category: 'calendar',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '30 minutes',
    levelKey: 'artist_ceo',
    prerequisites: ['artist_growth_loop'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 125 },
    priorityScore: 106,
    sortOrder: 30,
  },
  {
    key: 'artist_revenue_milestone',
    title: 'Reach your direct-to-fan revenue milestone',
    subtitle: 'Real money from people who choose you',
    whyItMatters: 'Direct revenue is the point. Passing your first milestone proves the whole system pays.',
    category: 'revenue',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'hard',
    estimatedTime: 'ongoing',
    levelKey: 'artist_ceo',
    prerequisites: ['artist_growth_loop'],
    // cents; personalized. $100 net keeps the milestone reachable for any artist size.
    completionCondition: { kind: 'domain', check: 'artist_revenue_milestone', count: 10000 },
    reward: { xp: 200, badges: ['first_revenue_milestone'] },
    priorityScore: 104,
    sortOrder: 40,
  },
  {
    key: 'artist_90_day_plan',
    title: 'Create your 90-day growth plan',
    subtitle: 'Decide the next quarter on purpose',
    whyItMatters: 'A 90-day plan turns momentum into a direction. It is how a hobby becomes a business you run.',
    category: 'calendar',
    questType: 'main_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '30 minutes',
    levelKey: 'artist_ceo',
    prerequisites: ['artist_growth_loop'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 150, badges: ['ceo_plan'] },
    priorityScore: 102,
    sortOrder: 50,
  },
  {
    key: 'artist_team_split',
    title: 'Add a legitimate collaborator split',
    subtitle: 'Only when a real collaborator relationship needs it',
    whyItMatters:
      'When someone truly helps build your movement, a fair split keeps them invested. Add one only for a real deal, never as busywork.',
    category: 'team',
    questType: 'side_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '15 minutes',
    levelKey: 'artist_ceo',
    prerequisites: ['artist_growth_loop'],
    completionCondition: { kind: 'domain', check: 'artist_has_team_split' },
    reward: { xp: 100 },
    priorityScore: 100,
    sortOrder: 60,
  },
  {
    key: 'artist_beat_rise_mode',
    title: 'Build a self-sustaining CRWN business',
    subtitle: 'The final boss: an artist-owned business',
    whyItMatters:
      'This is the whole game: a complete profile, an organized vault, a working ladder, payments live, a free and paid path, real supporters, delivered benefits, a closed campaign, referrals on, and positive revenue. Beat it and you own your audience.',
    category: 'revenue',
    questType: 'boss_quest',
    requiredRole: 'artist',
    difficulty: 'boss',
    estimatedTime: 'the whole journey',
    levelKey: 'artist_ceo',
    prerequisites: ['artist_growth_loop'],
    completionCondition: { kind: 'domain', check: 'artist_beat_rise_mode' },
    reward: { xp: 1000, badges: ['rise_mode_champion'], unlocks: ['empire_mode'], notifyFans: true },
    priorityScore: 98,
    sortOrder: 70,
  },
];

// ---------------------------------------------------------------------------
// ARTIST — Empire Mode (endgame). Repeatable SCALING via escalating, non-repeatable
// milestones (each completes once, so no XP farming) plus manual seasonal quests.
// Each milestone gates on the prior rung so an established artist enters at the right
// step instead of redoing beginner tasks.
// ---------------------------------------------------------------------------
const ARTIST_EMPIRE: QuestTemplate[] = [
  {
    key: 'artist_empire_25',
    title: 'Reach 25 supporters',
    category: 'support',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'hard',
    levelKey: 'empire',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_supporter_count', count: 25 },
    reward: { xp: 300, badges: ['supporters_25'] },
    priorityScore: 90,
    sortOrder: 10,
  },
  {
    key: 'artist_empire_50',
    title: 'Reach 50 supporters',
    category: 'support',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'hard',
    levelKey: 'empire',
    prerequisites: ['artist_empire_25'],
    completionCondition: { kind: 'domain', check: 'artist_supporter_count', count: 50 },
    reward: { xp: 400, badges: ['supporters_50'] },
    priorityScore: 89,
    sortOrder: 20,
  },
  {
    key: 'artist_empire_100',
    title: 'Reach 100 supporters',
    category: 'support',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'boss',
    levelKey: 'empire',
    prerequisites: ['artist_empire_50'],
    completionCondition: { kind: 'domain', check: 'artist_supporter_count', count: 100 },
    reward: { xp: 600, badges: ['supporters_100'], notifyFans: true },
    priorityScore: 88,
    sortOrder: 30,
  },
  {
    key: 'artist_empire_250',
    title: 'Reach 250 supporters',
    category: 'support',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'boss',
    levelKey: 'empire',
    prerequisites: ['artist_empire_100'],
    completionCondition: { kind: 'domain', check: 'artist_supporter_count', count: 250 },
    reward: { xp: 800, badges: ['supporters_250'], notifyFans: true },
    priorityScore: 87,
    sortOrder: 40,
  },
  {
    key: 'artist_empire_500',
    title: 'Reach 500 supporters',
    category: 'support',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'boss',
    levelKey: 'empire',
    prerequisites: ['artist_empire_250'],
    completionCondition: { kind: 'domain', check: 'artist_supporter_count', count: 500 },
    reward: { xp: 1200, badges: ['supporters_500'], notifyFans: true },
    priorityScore: 86,
    sortOrder: 50,
  },
  {
    key: 'artist_empire_mrr_1k',
    title: 'Reach $1,000 per month in recurring support',
    category: 'revenue',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'boss',
    levelKey: 'empire',
    prerequisites: ['artist_first_supporter'],
    completionCondition: { kind: 'domain', check: 'artist_mrr_milestone', count: 100000 },
    reward: { xp: 700, badges: ['mrr_1k'] },
    priorityScore: 85,
    sortOrder: 60,
  },
  {
    key: 'artist_empire_mrr_5k',
    title: 'Reach $5,000 per month in recurring support',
    category: 'revenue',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'boss',
    levelKey: 'empire',
    prerequisites: ['artist_empire_mrr_1k'],
    completionCondition: { kind: 'domain', check: 'artist_mrr_milestone', count: 500000 },
    reward: { xp: 1200, badges: ['mrr_5k'], notifyFans: true },
    priorityScore: 84,
    sortOrder: 70,
  },
  {
    key: 'artist_empire_referrals',
    title: 'Drive 10 referred supporters',
    category: 'promotion',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'hard',
    levelKey: 'empire',
    prerequisites: ['artist_activate_referrals'],
    completionCondition: { kind: 'domain', check: 'artist_referral_conversions', count: 10 },
    reward: { xp: 500, badges: ['referral_engine'] },
    priorityScore: 83,
    sortOrder: 80,
  },
  {
    key: 'artist_empire_city',
    title: 'Unlock your first city',
    category: 'city',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'hard',
    levelKey: 'empire',
    prerequisites: ['artist_ten_supporters'],
    completionCondition: { kind: 'domain', check: 'artist_cities_unlocked', count: 1 },
    reward: { xp: 500, badges: ['first_city'] },
    priorityScore: 82,
    sortOrder: 90,
  },
  {
    key: 'artist_empire_release',
    title: 'Run a fan-powered release cycle',
    subtitle: 'Presell, launch, and deliver a project through CRWN',
    category: 'campaign',
    questType: 'questline_step',
    requiredRole: 'artist',
    difficulty: 'boss',
    levelKey: 'empire',
    prerequisites: ['artist_campaign_closed'],
    completionCondition: { kind: 'manual' },
    reward: { xp: 600, badges: ['release_cycle'] },
    priorityScore: 81,
    sortOrder: 100,
  },
];

// ---------------------------------------------------------------------------
// FAN — Stage 1: Discover
// ---------------------------------------------------------------------------
const FAN_DISCOVER: QuestTemplate[] = [
  {
    key: 'fan_listen_first_track',
    title: "Listen to a track",
    subtitle: 'Start with the music',
    category: 'discovery',
    questType: 'onboarding_quest',
    requiredRole: 'fan',
    difficulty: 'easy',
    estimatedTime: 'under 2 minutes',
    levelKey: 'discover',
    completionCondition: { kind: 'fan_event', eventType: 'like', scope: 'fan', count: 1 },
    reward: { xp: 10, badges: ['listener'] },
    priorityScore: 200,
    sortOrder: 10,
  },
];

// ---------------------------------------------------------------------------
// FAN — Stage 2: Support (+ connected campaign quests)
// ---------------------------------------------------------------------------
const FAN_SUPPORT: QuestTemplate[] = [
  {
    key: 'fan_subscribe_to_artist',
    title: 'Become a supporter',
    subtitle: 'Join a tier and unlock supporter perks',
    whyItMatters: 'Supporting early is how you prove you were here first, and it directly funds the rise.',
    category: 'support',
    questType: 'daily_assignment',
    requiredRole: 'fan',
    difficulty: 'medium',
    estimatedTime: '5 minutes',
    levelKey: 'support',
    completionCondition: { kind: 'domain', check: 'fan_has_subscription' },
    reward: { xp: 100, badges: ['supporter', 'day_one'], proofCard: true },
    priorityScore: 190,
    sortOrder: 10,
  },
  {
    key: 'fan_back_campaign',
    title: "Back the campaign",
    subtitle: 'Help push the current mission over the line',
    whyItMatters: 'Backers are named on the wall. This is the moment you become part of the story.',
    category: 'support',
    questType: 'campaign_quest',
    requiredRole: 'fan',
    difficulty: 'medium',
    estimatedTime: '5 minutes',
    levelKey: 'support',
    // Matches the signal the existing /api/road-campaigns/[id]/support route emits
    // (event_type 'custom', ref_kind 'campaign'). Money-campaign backing is refined
    // in Phase 3 when the connected campaign fan-out is wired.
    completionCondition: { kind: 'fan_event', eventType: 'custom', refKind: 'campaign', scope: 'fan', count: 1 },
    reward: { xp: 100, proofCard: true },
    priorityScore: 185,
    sortOrder: 20,
  },
  {
    key: 'fan_share_campaign',
    title: 'Share the campaign',
    subtitle: 'Post the campaign clip and bring people in',
    whyItMatters: 'One share can bring the supporter that unlocks the goal. Your reach is the artist’s reach.',
    category: 'promotion',
    questType: 'daily_assignment',
    requiredRole: 'fan',
    difficulty: 'easy',
    estimatedTime: 'under 2 minutes',
    levelKey: 'support',
    completionCondition: { kind: 'fan_event', eventType: 'share', refKind: 'campaign', scope: 'fan', count: 1 },
    reward: { xp: 25, proofCard: true },
    repeatable: true,
    priorityScore: 180,
    sortOrder: 30,
  },
  {
    key: 'fan_invite_friend',
    title: 'Invite one friend',
    subtitle: 'Bring someone into the movement',
    whyItMatters: 'Referrals are the highest-impact thing a fan can do, and they can earn you commission.',
    category: 'promotion',
    questType: 'daily_assignment',
    requiredRole: 'fan',
    difficulty: 'easy',
    estimatedTime: '5 minutes',
    levelKey: 'support',
    completionCondition: { kind: 'domain', check: 'fan_referral_count', count: 1 },
    reward: { xp: 50, badges: ['promoter'], proofCard: true },
    repeatable: true,
    priorityScore: 175,
    sortOrder: 40,
  },
];

// ---------------------------------------------------------------------------
// LIVE QUEST MODE — on-demand artist quests streamed with fans participating.
// Minimal set (3 types); more are data additions against this same shape. These
// are NOT auto-assigned — the artist starts one from the Live Quest launcher,
// which ties it to a live session and spawns the connected fan quests.
// ---------------------------------------------------------------------------
const LIVE_QUESTS: QuestTemplate[] = [
  {
    key: 'live_build_offer',
    title: 'Build an Offer (Live)',
    subtitle: 'Create your supporter offer with fans in the room',
    whyItMatters: 'Building live turns a solo task into a moment. Fans tell you what they want and buy it on the spot.',
    category: 'offer',
    questType: 'live_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '30 minutes',
    completionCondition: { kind: 'domain', check: 'artist_has_offer' },
    reward: { xp: 150, badges: ['live_commander'], content: ['rise_feed_offer_post'] },
    canStreamLive: true,
    onDemand: true,
    priorityScore: 120,
    generatesFanQuests: ['fan_subscribe_to_artist'],
  },
  {
    key: 'live_launch_campaign',
    title: 'Launch a Campaign (Live)',
    subtitle: 'Set a goal and rally the room to hit it',
    whyItMatters: 'A campaign launched live gets its first backers before the stream ends. Momentum is the whole game.',
    category: 'campaign',
    questType: 'live_quest',
    requiredRole: 'artist',
    difficulty: 'hard',
    estimatedTime: '30 minutes',
    completionCondition: { kind: 'domain', check: 'artist_has_campaign' },
    reward: { xp: 200, badges: ['live_commander'], content: ['campaign_share_card'] },
    canStreamLive: true,
    onDemand: true,
    priorityScore: 120,
    generatesFanQuests: ['fan_back_campaign', 'fan_share_campaign', 'fan_invite_friend'],
  },
  {
    key: 'live_final_push',
    title: 'Campaign Final Push (Live)',
    subtitle: 'Countdown live while fans share, buy, and clip',
    whyItMatters: 'The last hours decide it. A live push converts the fence-sitters who were waiting for a reason.',
    category: 'campaign',
    questType: 'live_quest',
    requiredRole: 'artist',
    difficulty: 'medium',
    estimatedTime: '1 hour',
    completionCondition: { kind: 'manual' },
    reward: { xp: 150, content: ['campaign_share_card'] },
    canStreamLive: true,
    onDemand: true,
    priorityScore: 115,
    generatesFanQuests: ['fan_share_campaign', 'fan_back_campaign', 'fan_invite_friend'],
  },
];

const ALL_TEMPLATES: QuestTemplate[] = [
  ...ARTIST_SETUP,
  ...ARTIST_OPEN_GATES,
  ...ARTIST_FIRST_SUPPORTERS,
  ...ARTIST_COMMUNITY,
  ...ARTIST_CAMPAIGN_STARTER,
  ...ARTIST_GROWTH,
  ...ARTIST_CEO,
  ...ARTIST_EMPIRE,
  ...LIVE_QUESTS,
  ...FAN_DISCOVER,
  ...FAN_SUPPORT,
];

export const QUEST_TEMPLATES: Record<string, QuestTemplate> = Object.fromEntries(
  ALL_TEMPLATES.map((t) => [t.key, t]),
);

export function getTemplate(key: string): QuestTemplate | undefined {
  return QUEST_TEMPLATES[key];
}

export function templatesForRole(role: 'artist' | 'fan'): QuestTemplate[] {
  // On-demand quests (live quests) are excluded — they're started explicitly,
  // never auto-assigned by ensureRoleQuests.
  return ALL_TEMPLATES.filter((t) => t.requiredRole === role && !t.onDemand).sort(
    (a, b) => (b.priorityScore ?? 0) - (a.priorityScore ?? 0),
  );
}

/** The on-demand Live Quest templates an artist can start from the launcher. */
export function liveQuestTemplates(): QuestTemplate[] {
  return ALL_TEMPLATES.filter((t) => t.onDemand && t.requiredRole === 'artist');
}

/** Fan quest template keys an artist quest spawns for supporters. */
export function fanQuestsForArtistTemplate(key: string): string[] {
  return getTemplate(key)?.generatesFanQuests ?? [];
}

/**
 * Upsert the code catalog into quest_templates (idempotent, by key). Call from an
 * admin/cron route after deploy so the DB catalog matches code. Best-effort.
 */
export async function syncTemplatesToDb(admin: any): Promise<{ synced: number }> {
  let synced = 0;
  for (const t of ALL_TEMPLATES) {
    try {
      const { error } = await admin.from('quest_templates').upsert(
        {
          key: t.key,
          title: t.title,
          subtitle: t.subtitle ?? null,
          description: t.description ?? null,
          why_it_matters: t.whyItMatters ?? null,
          category: t.category,
          quest_type: t.questType,
          required_role: t.requiredRole,
          difficulty: t.difficulty,
          estimated_time: t.estimatedTime ?? null,
          required_feature: t.requiredFeature ?? null,
          level_key: t.levelKey ?? null,
          prerequisites: t.prerequisites ?? [],
          steps: t.steps ?? [],
          completion_condition: t.completionCondition,
          reward: t.reward ?? {},
          unlocks: t.unlocks ?? [],
          build_tags: t.buildTags ?? [],
          can_stream_live: t.canStreamLive ?? false,
          repeatable: t.repeatable ?? false,
          priority_score: t.priorityScore ?? 100,
          sort_order: t.sortOrder ?? 0,
          source: 'system',
          created_by: 'system',
          is_active: true,
          updated_at: new Date().toISOString(),
        },
        { onConflict: 'key' },
      );
      if (!error) synced++;
    } catch (err) {
      console.error('[quests] syncTemplate failed:', t.key, err);
    }
  }
  return { synced };
}
