// Asset resolution with provenance. Every visual that is not generated by the
// composition itself (footage, sheets, sourced B-roll, the end card) comes through here
// with a provenance record, and the renderer refuses an asset without one.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const REPO = path.resolve(HERE, "../../..");

export function loadLibrary(file = path.join(HERE, "..", "assets.json")) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

/** Sheet file for sheet N (1-based), matching generate-fan-economy-images.mjs. */
export const sheetFile = (slug, n) => (n === 1 ? `${slug}.jpg` : `${slug}-${n}.jpg`);

/**
 * The script's printed sheets, each with its editorial role by POSITION FROM THE END
 * (FE-SKILL-008): last = cta, last-but-one = reveal, first = hook, a sheet that
 * letters CRWN (the five-sheet format's sheet 3) = crwn, anything else = middle.
 */
export function resolveSheets(slug, library, { exists = fs.existsSync, readCrwn = null } = {}) {
  const dir = library.sheets.dir;
  const present = [];
  for (let n = 1; n <= 5; n++) {
    const p = path.join(dir, sheetFile(slug, n));
    if (exists(p)) present.push({ n, path: p });
    else break;
  }
  const count = present.length;
  return present.map(({ n, path: p }) => {
    let role = "middle";
    if (n === 1) role = "hook";
    if (count >= 4 && n === count) role = "cta";
    if (count >= 3 && n === count - (count >= 4 ? 1 : 0)) role = "reveal";
    if (count === 5 && n === 3) role = "crwn";
    if (readCrwn && readCrwn(n)) role = "crwn";
    return { id: `sheet-${n}`, kind: "sheet", n, path: p, role, gatedToReveal: role === "reveal" || role === "cta", provenance: library.sheets.provenance };
  });
}

/** Sourced B-roll dropped into <project>/broll with a provenance sidecar. */
export function resolveBroll(projectDir) {
  const dir = path.join(projectDir, "broll");
  if (!fs.existsSync(dir)) return { assets: [], refused: [] };
  const assets = [], refused = [];
  for (const f of fs.readdirSync(dir)) {
    if (f.endsWith(".json")) continue;
    if (!/\.(mp4|mov|webm|m4v|jpg|jpeg|png|webp)$/i.test(f)) continue;
    const side = path.join(dir, f.replace(/\.[^.]+$/, ".json"));
    if (!fs.existsSync(side)) { refused.push({ file: f, reason: "no provenance sidecar (.json with source, url, rights)" }); continue; }
    let meta;
    try { meta = JSON.parse(fs.readFileSync(side, "utf8")); } catch { refused.push({ file: f, reason: "sidecar is not valid JSON" }); continue; }
    if (!meta.source || !meta.rights) { refused.push({ file: f, reason: "sidecar needs at least source and rights" }); continue; }
    assets.push({
      id: `broll-${f.replace(/\.[^.]+$/, "").replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`,
      kind: /\.(jpg|jpeg|png|webp)$/i.test(f) ? "broll_image" : "broll_video",
      path: path.join(dir, f),
      shows: meta.shows || null,
      reveals: meta.reveals || [],
      line: meta.line ?? null,
      provenance: { source: meta.source, url: meta.url || null, rights: meta.rights },
    });
  }
  return { assets, refused };
}

/** Lead-magnet slug -> the public tool's name, read from the product's own registry. */
export function toolNames(repo = REPO) {
  const src = fs.readFileSync(path.join(repo, "src/lib/leadMagnets/registry.ts"), "utf8");
  const names = { worth: "What your fanbase is worth" };
  const re = /slug:\s*'([a-z0-9-]+)',\s*\n\s*name:\s*'([^']+)'/g;
  for (const m of src.matchAll(re)) names[m[1]] = m[2];
  return names;
}

export function missingFiles(library) {
  return Object.entries(library.library).filter(([, a]) => a.path && !fs.existsSync(a.path)).map(([id, a]) => ({ id, path: a.path }));
}
